# This is a complete GitHub Actions workflow file.

name: Deploy to Kubernetes

# 1. TRIGGER: This workflow runs on any push to the 'main' branch.
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 2. CHECKOUT: Checks out your repository's code so the workflow can access it.
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      # 3. LOGIN (Your integrated step): Creates the kubeconfig file from a secret.
      - name: 2. Log into Kubernetes
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          echo "✅ Kubeconfig file created. Verifying connection..."
          kubectl cluster-info

      # 4. DEPLOY: Uses the connection to apply Kubernetes manifests from your repository.
      - name: 3. Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          echo "🚀 Deployment successful!"